eclipse/rdf4j#2101 document use of writable property
eclipse/rdf4j-doc pull request #148
Opened 2020-04-24 04:08 UTC by jeenbroekstra

- some minor editorial changes as well

2020-04-24 06:15 UTC, aschwarte10 requested changes
Looks good, I would like to more generalize this example to not point users into the direction that local NativeStore repositories should be used. I will provide a commit on-top, feel free to accept or remove and then merge

Maybe in the future, when we have more complex write-strategies we require to spend a seperate paragraph

2020-04-24 06:15 UTC, aschwarte10 commented on site/content/documentation/programming/federation/index.md
> +### Example 4: Local Federation with writable endpoint (NativeStore):
This should be "Example 5"

As best practice I would suggest to also not restrict writability to a local federation with NativeStore (from the documentation perspective) => we should encourage users to rather move to repository manager based solutions and resolvable repositories (which of course then can be NativeStore). This is a more stable environment.

If you are OK, I will provide a commit on top

2020-04-24 06:33 UTC, aschwarte10 approved these changes

2020-04-24 06:34 UTC, aschwarte10 commented
I have added another commit on top and tried to generalize this a bit. Please have a look and refine as need, then this change can be merged

2020-04-27 04:24 UTC, abrokenjester reviewed
Looks good, thanks @aschwarte10

2020-04-29 02:03 UTC, merged