GH-56 renamed to sparqlbuilder and integrated in main doco
eclipse/rdf4j-doc pull request #58
Opened 2018-06-10 04:42 UTC by jeenbroekstra

2018-06-12 05:48 UTC, anqit requested changes

2018-06-12 05:48 UTC, anqit commented on doc/sparqlbuilder/05-graph-patterns.adoc
> +Variable x = SparqlBuilder.var("x"), name = Spanqit.var("name");
Missed one, here

2018-06-12 05:48 UTC, anqit commented on doc/sparqlbuilder/05-graph-patterns.adoc
> +SparqlBuilder uses three classes to represent the SPARQL graph patterns, all of which implement the {javadoc}sparqlbuilder/graphpattern/GraphPatter.html[GraphPattern] interface:
typo ("GraphPatter")

2018-06-22 01:34 UTC, jeenbroekstra commented
@anqit thanks for the feedback, fixed!

2018-06-22 01:53 UTC, merged